# Generated by Django 6.0.6 on 2026-07-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('ozet', models.CharField(max_length=300)),
                ('icerik', models.TextField()),
                ('gorsel_url', models.URLField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yayinda_mi', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
