# Generated by Django 6.0.6 on 2026-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_yazi_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('eposta', models.EmailField(max_length=254)),
                ('mesaj', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
